In [1]:
import pandas as pd

In [2]:
matches=pd.read_csv('matches.csv')
deliveries=pd.read_csv('deliveries.csv')

In [3]:
matches.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [4]:
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

MERGE THE DATA

In [5]:
data=deliveries.merge(matches,left_on='match_id',right_on='id')
data.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN

In [6]:
data.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder', 'id', 'Season', 'city', 'date', 'team1',
       'team2', 'toss_winner', 'toss_decision', 'result', 'dl_applied',
       'winner', 'win_by_runs', 'win_by_wickets', 'player_of_match', 'venue',
       'umpire1', 'umpire2', 'umpire3'],
      dtype='object')

In [7]:
data.shape

(179078, 39)

In [8]:
data.describe()

,match_id,inning,over,ball,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,id,dl_applied,win_by_runs,win_by_wickets
count,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000
mean,1802.252957,1.482952,10.162488,3.615587,0.000452,0.036721,0.004936,0.021136,0.004183,0.000056,1.246864,0.067032,1.313897,1802.252957,0.017914,13.404036,3.261579
std,3472.322805,0.502074,5.677684,1.806966,0.021263,0.251161,0.116480,0.194908,0.070492,0.016709,1.608270,0.342553,1.605422,3472.322805,0.132639,23.261007,3.347033
min,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,190.000000,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,190.000000,0.000000,0.000000,0.000000
50%,379.000000,1.000000,10.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,379.000000,0.000000,0.000000,3.000000
75%,567.000000,2.000000,15.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,567.000000,0.000000,19.000000,6.000000
max,11415.000000,5.000000,20.000000,9.000000,1.000000,5.000000,4.000000,5.000000,5.000000,5.000000,7.000000,7.000000,10.000000,11415.000000,1.000000,146.000000,10.000000

In [9]:
data.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
is_super_over            0
wide_runs                0
bye_runs                 0
legbye_runs              0
noball_runs              0
penalty_runs             0
batsman_runs             0
extra_runs               0
total_runs               0
player_dismissed    170244
dismissal_kind      170244
fielder             172630
id                       0
Season                   0
city                  1700
date                     0
team1                    0
team2                    0
toss_winner              0
toss_decision            0
result                   0
dl_applied               0
winner                 372
win_by_runs              0
win_by_wickets           0
player_of_match        372
venue                    0
umpire1                500
umpire2                500
umpire3             150712
dtype: int64

There are many columns which is not used for prediction so you could remove it

In [10]:
data['is_wicket'] = data['player_dismissed'].notnull().astype(int)

In [11]:
keep_columns = [
    'match_id','inning','batting_team','bowling_team',
    'over','ball','total_runs','is_wicket',
    'winner','venue'
]

data = data[keep_columns]

In [12]:
data.head()

,match_id,inning,batting_team,bowling_team,over,ball,total_runs,is_wicket,winner,venue
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,0,0,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,0,0,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,4,0,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,0,0,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,2,0,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal"

In [13]:
data.isnull().sum()

match_id          0
inning            0
batting_team      0
bowling_team      0
over              0
ball              0
total_runs        0
is_wicket         0
winner          372
venue             0
dtype: int64

In [14]:
#2nd innings
data=data.query('inning==2')

In [15]:
# 1
temp = deliveries.merge(matches, left_on='match_id', right_on='id')
temp = temp[temp['inning'] == 1]

# 2
target_df = temp.groupby('match_id')['total_runs'].sum().reset_index()
target_df['target'] = target_df['total_runs'] + 1

# 3
data = data.merge(target_df[['match_id','target']], on='match_id')

# 4
data['runs_left'] = data['target'] - data['total_runs']

In [16]:
#wickets left
data['wickets'] = data.groupby('match_id')['is_wicket'].cumsum()
data['wickets_left'] = 10 - data['wickets']

In [17]:
#ball_left_columns
data['balls_left'] = 120 - (data['over']*6 + data['ball'])

In [18]:
#required run rate
data['rrr'] = (data['runs_left'] * 6) / data['balls_left']

In [19]:
data.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'total_runs', 'is_wicket', 'winner', 'venue', 'target', 'runs_left',
       'wickets', 'wickets_left', 'balls_left', 'rrr'],
      dtype='object')

In [20]:
data.head()

,match_id,inning,batting_team,bowling_team,over,ball,total_runs,is_wicket,winner,venue,target,runs_left,wickets,wickets_left,balls_left,rrr
0,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,1,0,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",208,207,0,10,113,10.991150
1,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,0,0,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",208,208,0,10,112,11.142857
2,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,0,0,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",208,208,0,10,111,11.243243
3,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,2,0,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",208,206,0,10,110,11.236364
4,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,4,0,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",208,204,0,10,109,11.229358

In [21]:
data['result'] = (data['batting_team'] == data['winner']).astype(int)

In [22]:
import numpy as np

# infinity to nan
data.replace([np.inf, -np.inf], np.nan, inplace=True)

# nan is removed
data = data.dropna()

In [23]:
#final features

In [24]:
#targeting columns for modals
features = [
    'batting_team',
    'bowling_team',
    'venue',
    'runs_left',
    'balls_left',
    'wickets_left',
    'rrr'
]

X = data[features]
y = data['result']

In [25]:
#encoding
X = pd.get_dummies(X)

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=42)

In [27]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=10000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [28]:
#accuracy
print(model.score(X_test, y_test))

0.7864508001679653

In [29]:
import pickle

pickle.dump(model, open('ipl_winning.pkl', 'wb'))
pickle.dump(X.columns, open('columns.pkl', 'wb'))